/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IDonorChain,
  IDonorChainInterface,
} from "../../../contracts/DonorBadgeNFT.sol/IDonorChain";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "getPublicCount",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IDonorChain__factory {
  static readonly abi = _abi;
  static createInterface(): IDonorChainInterface {
    return new Interface(_abi) as IDonorChainInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IDonorChain {
    return new Contract(address, _abi, runner) as unknown as IDonorChain;
  }
}
