/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { DonorBadgeNFT__factory } from "./DonorBadgeNFT__factory";
export { IDonorChain__factory } from "./IDonorChain__factory";
