/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DonorChainInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "getEncryptedCountOf"
      | "getMyEncryptedCount"
      | "getMyEncryptedLastVolume"
      | "getPublicCount"
      | "protocolId"
      | "submitDonation"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "VitalRecordLogged"): EventFragment;

  encodeFunctionData(
    functionFragment: "getEncryptedCountOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMyEncryptedCount",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getMyEncryptedLastVolume",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getPublicCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "submitDonation",
    values: [
      BytesLike,
      BytesLike,
      string,
      BigNumberish,
      BytesLike,
      BytesLike,
      BigNumberish,
      BigNumberish
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "getEncryptedCountOf",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyEncryptedCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMyEncryptedLastVolume",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPublicCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "submitDonation",
    data: BytesLike
  ): Result;
}

export namespace VitalRecordLoggedEvent {
  export type InputTuple = [
    user: AddressLike,
    ipfsCid: string,
    date: BigNumberish,
    locationHash: BytesLike,
    hospitalHash: BytesLike,
    donationCategory: BigNumberish,
    transparentVolume: BigNumberish,
    encVolume: BytesLike
  ];
  export type OutputTuple = [
    user: string,
    ipfsCid: string,
    date: bigint,
    locationHash: string,
    hospitalHash: string,
    donationCategory: bigint,
    transparentVolume: bigint,
    encVolume: string
  ];
  export interface OutputObject {
    user: string;
    ipfsCid: string;
    date: bigint;
    locationHash: string;
    hospitalHash: string;
    donationCategory: bigint;
    transparentVolume: bigint;
    encVolume: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DonorChain extends BaseContract {
  connect(runner?: ContractRunner | null): DonorChain;
  waitForDeployment(): Promise<this>;

  interface: DonorChainInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  getEncryptedCountOf: TypedContractMethod<
    [user: AddressLike],
    [string],
    "view"
  >;

  getMyEncryptedCount: TypedContractMethod<[], [string], "view">;

  getMyEncryptedLastVolume: TypedContractMethod<[], [string], "view">;

  getPublicCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  submitDonation: TypedContractMethod<
    [
      inputVolume: BytesLike,
      inputProof: BytesLike,
      ipfsCid: string,
      date: BigNumberish,
      locationHash: BytesLike,
      hospitalHash: BytesLike,
      donationCategory: BigNumberish,
      transparentVolume: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "getEncryptedCountOf"
  ): TypedContractMethod<[user: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "getMyEncryptedCount"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getMyEncryptedLastVolume"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getPublicCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "submitDonation"
  ): TypedContractMethod<
    [
      inputVolume: BytesLike,
      inputProof: BytesLike,
      ipfsCid: string,
      date: BigNumberish,
      locationHash: BytesLike,
      hospitalHash: BytesLike,
      donationCategory: BigNumberish,
      transparentVolume: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "VitalRecordLogged"
  ): TypedContractEvent<
    VitalRecordLoggedEvent.InputTuple,
    VitalRecordLoggedEvent.OutputTuple,
    VitalRecordLoggedEvent.OutputObject
  >;

  filters: {
    "VitalRecordLogged(address,string,uint64,bytes32,bytes32,uint8,uint32,bytes32)": TypedContractEvent<
      VitalRecordLoggedEvent.InputTuple,
      VitalRecordLoggedEvent.OutputTuple,
      VitalRecordLoggedEvent.OutputObject
    >;
    VitalRecordLogged: TypedContractEvent<
      VitalRecordLoggedEvent.InputTuple,
      VitalRecordLoggedEvent.OutputTuple,
      VitalRecordLoggedEvent.OutputObject
    >;
  };
}
