/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IVitalChain,
  IVitalChainInterface,
} from "../../../contracts/HonorBadgeNFT.sol/IVitalChain";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "publicCount",
    outputs: [
      {
        internalType: "uint32",
        name: "",
        type: "uint32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
] as const;

export class IVitalChain__factory {
  static readonly abi = _abi;
  static createInterface(): IVitalChainInterface {
    return new Interface(_abi) as IVitalChainInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IVitalChain {
    return new Contract(address, _abi, runner) as unknown as IVitalChain;
  }
}
